
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef ENGINE_H
#define ENGINE_H
#include <stdint.h>
#include <math.h>
#include "vultin.h"
#include "engine.tables.h"

static_inline fix16_t Processor_sine_table_raw_c0(int index){
   return pgm_read_word_near(Processor_sine_table_c0 + index);
};

static_inline fix16_t Processor_sine_table_raw_c1(int index){
   return pgm_read_word_near(Processor_sine_table_c1 + index);
};

static_inline fix16_t Processor_sine_table_raw_c2(int index){
   return pgm_read_word_near(Processor_sine_table_c2 + index);
};

static_inline fix16_t Processor_sine_table(fix16_t x){
   int index;
   index = int_clip(fix_to_int(fix_mul(0x3ff0000 /* 1023.000000 */,x)),0,1023);
   return (pgm_read_word_near(fix_wrap_array(Processor_sine_table_c0) + index) + fix_mul(x,(pgm_read_word_near(fix_wrap_array(Processor_sine_table_c1) + index) + fix_mul(x,pgm_read_word_near(fix_wrap_array(Processor_sine_table_c2) + index)))));
}

typedef struct Processor__ctx_type_4 {
   fix16_t phase;
} Processor__ctx_type_4;

typedef Processor__ctx_type_4 Processor_process_type;

static_inline void Processor__ctx_type_4_init(Processor__ctx_type_4 &_output_){
   Processor__ctx_type_4 _ctx;
   _ctx.phase = 0x0 /* 0.000000 */;
   _output_ = _ctx;
   return ;
}

static_inline void Processor_process_init(Processor__ctx_type_4 &_output_){
   Processor__ctx_type_4_init(_output_);
   return ;
}

static_inline fix16_t Processor_process(Processor__ctx_type_4 &_ctx, fix16_t fs){
   _ctx.phase = (_ctx.phase + fix_div(0x1b80000 /* 440.000000 */,fs));
   _ctx.phase = (_ctx.phase % 0x10000 /* 1.000000 */);
   return Processor_sine_table(_ctx.phase);
}



#endif // ENGINE_H
