
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "engine.h"

void Processor__ctx_type_4_init(Processor__ctx_type_4 &_output_){
   Processor__ctx_type_4 _ctx;
   _ctx.step = 0x0 /* 0.000000 */;
   _ctx.phase = 0x0 /* 0.000000 */;
   _ctx.fs = 0x0 /* 0.000000 */;
   _ctx.freq = 0x0 /* 0.000000 */;
   Processor_default(_ctx);
   _output_ = _ctx;
   return ;
}


