
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef SYNTHSAMPLERAUTHENTICSTRINGS_H
#define SYNTHSAMPLERAUTHENTICSTRINGS_H
#include <stdint.h>
#include <math.h>
#include "vultin.h"
#include "synthSamplerAuthenticStrings.tables.h"

static_inline fix16_t synthSamplerAuthenticStrings_Util_noteToFrequency(int note){
   return fix_mul(0x217 /* 0.008176 */,fix_exp(fix_mul(0xec9 /* 0.057762 */,int_to_fix(note))));
};

typedef struct synthSamplerAuthenticStrings_Util__ctx_type_1 {
   uint8_t pre;
} synthSamplerAuthenticStrings_Util__ctx_type_1;

typedef synthSamplerAuthenticStrings_Util__ctx_type_1 synthSamplerAuthenticStrings_Util_edge_type;

static_inline void synthSamplerAuthenticStrings_Util__ctx_type_1_init(synthSamplerAuthenticStrings_Util__ctx_type_1 &_output_){
   synthSamplerAuthenticStrings_Util__ctx_type_1 &_ctx = _output_;
   _ctx.pre = false;
   
   return ;
}

static_inline void synthSamplerAuthenticStrings_Util_edge_init(synthSamplerAuthenticStrings_Util__ctx_type_1 &_output_){
   synthSamplerAuthenticStrings_Util__ctx_type_1_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerAuthenticStrings_Util_edge(synthSamplerAuthenticStrings_Util__ctx_type_1 &_ctx, uint8_t x){
   uint8_t ret;
   ret = (x && bool_not(_ctx.pre));
   _ctx.pre = x;
   return ret;
}

static_inline fix16_t synthSamplerAuthenticStrings_Util_cubic_clipper(fix16_t x){
   if(x <= -0xaaaa /* -0.666667 */){
      return -0xaaaa /* -0.666667 */;
   }
   else
   {
      if(x >= 0xaaaa /* 0.666667 */){
         return 0xaaaa /* 0.666667 */;
      }
      else
      {
         return (x + fix_mul(fix_mul(fix_mul(-0x5555 /* -0.333333 */,x),x),x));
      }
   }
};

typedef struct synthSamplerAuthenticStrings_Util__ctx_type_3 {
   fix16_t pre_x;
} synthSamplerAuthenticStrings_Util__ctx_type_3;

typedef synthSamplerAuthenticStrings_Util__ctx_type_3 synthSamplerAuthenticStrings_Util_change_type;

static_inline void synthSamplerAuthenticStrings_Util__ctx_type_3_init(synthSamplerAuthenticStrings_Util__ctx_type_3 &_output_){
   synthSamplerAuthenticStrings_Util__ctx_type_3 &_ctx = _output_;
   _ctx.pre_x = 0x0 /* 0.000000 */;
   
   return ;
}

static_inline void synthSamplerAuthenticStrings_Util_change_init(synthSamplerAuthenticStrings_Util__ctx_type_3 &_output_){
   synthSamplerAuthenticStrings_Util__ctx_type_3_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerAuthenticStrings_Util_change(synthSamplerAuthenticStrings_Util__ctx_type_3 &_ctx, fix16_t x){
   uint8_t v;
   v = (_ctx.pre_x != x);
   _ctx.pre_x = x;
   return v;
}

typedef struct synthSamplerAuthenticStrings_Util__ctx_type_4 {
   fix16_t x;
} synthSamplerAuthenticStrings_Util__ctx_type_4;

typedef synthSamplerAuthenticStrings_Util__ctx_type_4 synthSamplerAuthenticStrings_Util_smooth_type;

static_inline void synthSamplerAuthenticStrings_Util__ctx_type_4_init(synthSamplerAuthenticStrings_Util__ctx_type_4 &_output_){
   synthSamplerAuthenticStrings_Util__ctx_type_4 &_ctx = _output_;
   _ctx.x = 0x0 /* 0.000000 */;
   
   return ;
}

static_inline void synthSamplerAuthenticStrings_Util_smooth_init(synthSamplerAuthenticStrings_Util__ctx_type_4 &_output_){
   synthSamplerAuthenticStrings_Util__ctx_type_4_init(_output_);
   return ;
}

static_inline fix16_t synthSamplerAuthenticStrings_Util_smooth(synthSamplerAuthenticStrings_Util__ctx_type_4 &_ctx, fix16_t input, fix16_t coeff){
   _ctx.x = (_ctx.x + fix_mul(coeff,(input + (- _ctx.x))));
   return _ctx.x;
}

static_inline fix16_t synthSamplerAuthenticStrings_Util_velocityToLevel(int velocity){
   velocity = int_clip(velocity,0,127);
   return fix_mul(0x204 /* 0.007874 */,int_to_fix(velocity));
}

static_inline int synthSamplerAuthenticStrings_SampleWrapper_sample_samples(){
   return 25491;
};

static_inline fix16_t synthSamplerAuthenticStrings_SampleWrapper_sample(int channel, int index){
   if(channel == 0){
      return fix_wrap_array(synthSamplerAuthenticStrings_SampleWrapper_sample_chan_0)[(index % 25491)];
   }
   return 0x0 /* 0.000000 */;
}

static_inline fix16_t synthSamplerAuthenticStrings_SampleWrapper_getSample(int index){
   return synthSamplerAuthenticStrings_SampleWrapper_sample(0,index);
};

static_inline int synthSamplerAuthenticStrings_SampleWrapper_getSampleSize(){
   return synthSamplerAuthenticStrings_SampleWrapper_sample_samples();
};

static_inline fix16_t synthSamplerAuthenticStrings_SampleWrapper_getSampleFs(){
   return 0x1e0000 /* 30.000000 */;
};

static_inline int synthSamplerAuthenticStrings_SampleWrapper_getSampleNote(){
   return 60;
};

static_inline uint8_t synthSamplerAuthenticStrings_SampleWrapper_isSampleLoop(){
   return false;
};

static_inline int synthSamplerAuthenticStrings_SampleWrapper_getSampleLoopStart(){
   return (-1);
};

static_inline int synthSamplerAuthenticStrings_SampleWrapper_getSampleLoopEnd(){
   return (-1);
};

typedef struct synthSamplerAuthenticStrings_Notes__ctx_type_0 {
   uint8_t poly;
   int notes[128];
   int nb_notes;
   int last_notes[128];
   uint8_t allowDuplicates;
} synthSamplerAuthenticStrings_Notes__ctx_type_0;

typedef synthSamplerAuthenticStrings_Notes__ctx_type_0 synthSamplerAuthenticStrings_Notes_setPoly_type;

void synthSamplerAuthenticStrings_Notes__ctx_type_0_init(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_output_);

static_inline void synthSamplerAuthenticStrings_Notes_setPoly_init(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Notes_setPoly(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_ctx, uint8_t flag){
   _ctx.poly = flag;
};

typedef synthSamplerAuthenticStrings_Notes__ctx_type_0 synthSamplerAuthenticStrings_Notes_getPoly_type;

static_inline void synthSamplerAuthenticStrings_Notes_getPoly_init(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerAuthenticStrings_Notes_getPoly(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_ctx){
   return _ctx.poly;
};

typedef synthSamplerAuthenticStrings_Notes__ctx_type_0 synthSamplerAuthenticStrings_Notes_setAllowDuplicates_type;

static_inline void synthSamplerAuthenticStrings_Notes_setAllowDuplicates_init(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Notes_setAllowDuplicates(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_ctx, uint8_t flag){
   _ctx.allowDuplicates = flag;
};

typedef synthSamplerAuthenticStrings_Notes__ctx_type_0 synthSamplerAuthenticStrings_Notes_default_type;

static_inline void synthSamplerAuthenticStrings_Notes_default_init(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Notes_default(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_ctx){
   synthSamplerAuthenticStrings_Notes_setPoly(_ctx,false);
   synthSamplerAuthenticStrings_Notes_setAllowDuplicates(_ctx,false);
}

typedef synthSamplerAuthenticStrings_Notes__ctx_type_0 synthSamplerAuthenticStrings_Notes_nbNotes_type;

static_inline void synthSamplerAuthenticStrings_Notes_nbNotes_init(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Notes__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerAuthenticStrings_Notes_nbNotes(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_ctx){
   return _ctx.nb_notes;
};

typedef synthSamplerAuthenticStrings_Notes__ctx_type_0 synthSamplerAuthenticStrings_Notes_firstNote_type;

static_inline void synthSamplerAuthenticStrings_Notes_firstNote_init(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Notes__ctx_type_0_init(_output_);
   return ;
}

int synthSamplerAuthenticStrings_Notes_firstNote(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_ctx);

typedef synthSamplerAuthenticStrings_Notes__ctx_type_0 synthSamplerAuthenticStrings_Notes_lastNote_type;

static_inline void synthSamplerAuthenticStrings_Notes_lastNote_init(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Notes__ctx_type_0_init(_output_);
   return ;
}

int synthSamplerAuthenticStrings_Notes_lastNote(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_ctx);

typedef synthSamplerAuthenticStrings_Notes__ctx_type_0 synthSamplerAuthenticStrings_Notes_noteOff_type;

static_inline void synthSamplerAuthenticStrings_Notes_noteOff_init(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Notes__ctx_type_0_init(_output_);
   return ;
}

uint8_t synthSamplerAuthenticStrings_Notes_noteOff(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_ctx, int note, int channel);

typedef synthSamplerAuthenticStrings_Notes__ctx_type_0 synthSamplerAuthenticStrings_Notes_noteOn_type;

static_inline void synthSamplerAuthenticStrings_Notes_noteOn_init(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Notes__ctx_type_0_init(_output_);
   return ;
}

uint8_t synthSamplerAuthenticStrings_Notes_noteOn(synthSamplerAuthenticStrings_Notes__ctx_type_0 &_ctx, int note, int velocity, int channel);

static_inline void synthSamplerAuthenticStrings_Buffer_buffer(fix16_t (&oBuff)[256]){
}

void synthSamplerAuthenticStrings_Buffer_buffer_large(fix16_t (&oBuff)[2048]);

typedef struct synthSamplerAuthenticStrings_Sampler__ctx_type_0 {
   uint8_t sustaining;
   uint8_t sustain;
   fix16_t step;
   int state;
   int size;
   int sampleNote;
   fix16_t sampleFs;
   uint8_t quickKill;
   fix16_t qkStep;
   int posBase;
   fix16_t pos;
   synthSamplerAuthenticStrings_Notes__ctx_type_0 playingnotes;
   fix16_t noteRatio;
   int nextVelocity;
   int nextNote;
   uint8_t loopy;
   int loopS;
   int loopE;
   fix16_t level;
   uint8_t gate;
   fix16_t fsRatio;
   fix16_t fs;
   uint8_t crossfade;
   fix16_t buffer_o[256];
   fix16_t buffer_cross[256];
} synthSamplerAuthenticStrings_Sampler__ctx_type_0;

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_updateStep_type;

void synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_);

static_inline void synthSamplerAuthenticStrings_Sampler_updateStep_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Sampler_updateStep(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx){
   _ctx.step = fix_mul(_ctx.fsRatio,_ctx.noteRatio);
};

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_setNote_type;

static_inline void synthSamplerAuthenticStrings_Sampler_setNote_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Sampler_setNote(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx, int note);

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_setLevel_type;

static_inline void synthSamplerAuthenticStrings_Sampler_setLevel_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Sampler_setLevel(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx, fix16_t newLevel){
   _ctx.level = newLevel;
};

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_process_type;

static_inline void synthSamplerAuthenticStrings_Sampler_process_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

fix16_t synthSamplerAuthenticStrings_Sampler_process(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx);

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_process_bufferTo_type;

static_inline void synthSamplerAuthenticStrings_Sampler_process_bufferTo_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Sampler_process_bufferTo(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx, int nb, fix16_t (&oBuffer)[256]);

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_process_buffer_type;

static_inline void synthSamplerAuthenticStrings_Sampler_process_buffer_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Sampler_process_buffer(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx, int nb){
   synthSamplerAuthenticStrings_Sampler_process_bufferTo(_ctx,nb,_ctx.buffer_o);
};

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_setSamplerate_type;

static_inline void synthSamplerAuthenticStrings_Sampler_setSamplerate_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Sampler_setSamplerate(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx, fix16_t newFs);

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_updateCrossFade_type;

static_inline void synthSamplerAuthenticStrings_Sampler_updateCrossFade_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Sampler_updateCrossFade(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx);

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_setLoop_type;

static_inline void synthSamplerAuthenticStrings_Sampler_setLoop_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Sampler_setLoop(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx, uint8_t loop){
   _ctx.loopy = loop;
};

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_setLoopStart_type;

static_inline void synthSamplerAuthenticStrings_Sampler_setLoopStart_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Sampler_setLoopStart(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx, int newLoopS){
   _ctx.loopS = int_clip(newLoopS,0,_ctx.size);
   synthSamplerAuthenticStrings_Sampler_updateCrossFade(_ctx);
}

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_setLoopEnd_type;

static_inline void synthSamplerAuthenticStrings_Sampler_setLoopEnd_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Sampler_setLoopEnd(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx, int newLoopE){
   _ctx.loopE = int_clip(newLoopE,0,_ctx.size);
   synthSamplerAuthenticStrings_Sampler_updateCrossFade(_ctx);
}

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_getLoop_type;

static_inline void synthSamplerAuthenticStrings_Sampler_getLoop_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerAuthenticStrings_Sampler_getLoop(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx){
   return _ctx.loopy;
};

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_getLoopStart_type;

static_inline void synthSamplerAuthenticStrings_Sampler_getLoopStart_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerAuthenticStrings_Sampler_getLoopStart(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx){
   return _ctx.loopS;
};

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_getLoopEnd_type;

static_inline void synthSamplerAuthenticStrings_Sampler_getLoopEnd_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerAuthenticStrings_Sampler_getLoopEnd(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx){
   return _ctx.loopE;
};

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_getSampleSize_type;

static_inline void synthSamplerAuthenticStrings_Sampler_getSampleSize_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerAuthenticStrings_Sampler_getSampleSize(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx){
   return _ctx.size;
};

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_setSustain_type;

static_inline void synthSamplerAuthenticStrings_Sampler_setSustain_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Sampler_setSustain(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx, uint8_t flag);

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_noteOn_type;

static_inline void synthSamplerAuthenticStrings_Sampler_noteOn_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

uint8_t synthSamplerAuthenticStrings_Sampler_noteOn(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx, int note, int velocity, int channel);

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_setPoly_type;

static_inline void synthSamplerAuthenticStrings_Sampler_setPoly_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Sampler_setPoly(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx, uint8_t flag){
   synthSamplerAuthenticStrings_Notes_setPoly(_ctx.playingnotes,flag);
};

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_noteOff_type;

static_inline void synthSamplerAuthenticStrings_Sampler_noteOff_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Sampler_noteOff(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx, int note, int channel);

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_0 synthSamplerAuthenticStrings_Sampler_default_type;

static_inline void synthSamplerAuthenticStrings_Sampler_default_init(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Sampler_default(synthSamplerAuthenticStrings_Sampler__ctx_type_0 &_ctx);

typedef struct synthSamplerAuthenticStrings_Sampler__ctx_type_1 {
   synthSamplerAuthenticStrings_Sampler__ctx_type_0 _inst1fd;
} synthSamplerAuthenticStrings_Sampler__ctx_type_1;

typedef synthSamplerAuthenticStrings_Sampler__ctx_type_1 synthSamplerAuthenticStrings_Sampler_dummy_type;

static_inline void synthSamplerAuthenticStrings_Sampler__ctx_type_1_init(synthSamplerAuthenticStrings_Sampler__ctx_type_1 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_1 &_ctx = _output_;
   synthSamplerAuthenticStrings_Sampler__ctx_type_0_init(_ctx._inst1fd);
   
   return ;
}

static_inline void synthSamplerAuthenticStrings_Sampler_dummy_init(synthSamplerAuthenticStrings_Sampler__ctx_type_1 &_output_){
   synthSamplerAuthenticStrings_Sampler__ctx_type_1_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Sampler_dummy(synthSamplerAuthenticStrings_Sampler__ctx_type_1 &_ctx){
   fix16_t buff[256];
   synthSamplerAuthenticStrings_Buffer_buffer(buff);
   synthSamplerAuthenticStrings_Sampler_process_bufferTo(_ctx._inst1fd,0,buff);
}

typedef struct synthSamplerAuthenticStrings_Poly__ctx_type_0 {
   synthSamplerAuthenticStrings_Sampler__ctx_type_0 voice3;
   synthSamplerAuthenticStrings_Sampler__ctx_type_0 voice2;
   synthSamplerAuthenticStrings_Sampler__ctx_type_0 voice1;
   synthSamplerAuthenticStrings_Sampler__ctx_type_0 voice0;
   uint8_t should_leftovers;
} synthSamplerAuthenticStrings_Poly__ctx_type_0;

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_getSample_type;

void synthSamplerAuthenticStrings_Poly__ctx_type_0_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_);

static_inline void synthSamplerAuthenticStrings_Poly_getSample_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

fix16_t synthSamplerAuthenticStrings_Poly_getSample(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, int voice);

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_runVoice_type;

static_inline void synthSamplerAuthenticStrings_Poly_runVoice_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_runVoice(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, int voice, int nb, fix16_t (&buff)[256]){
   switch(voice) {
      case 0:
         synthSamplerAuthenticStrings_Sampler_process_bufferTo(_ctx.voice0,nb,buff);
      break;
      case 1:
         synthSamplerAuthenticStrings_Sampler_process_bufferTo(_ctx.voice1,nb,buff);
      break;
      case 2:
         synthSamplerAuthenticStrings_Sampler_process_bufferTo(_ctx.voice2,nb,buff);
      break;
      case 3:
         synthSamplerAuthenticStrings_Sampler_process_bufferTo(_ctx.voice3,nb,buff);
      break;
    
   }
};

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_sendNoteOn_type;

static_inline void synthSamplerAuthenticStrings_Poly_sendNoteOn_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_sendNoteOn(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, int voice, int note, int velocity, int channel){
   switch(voice) {
      case 0:
         synthSamplerAuthenticStrings_Sampler_noteOn(_ctx.voice0,note,velocity,channel);
      break;
      case 1:
         synthSamplerAuthenticStrings_Sampler_noteOn(_ctx.voice1,note,velocity,channel);
      break;
      case 2:
         synthSamplerAuthenticStrings_Sampler_noteOn(_ctx.voice2,note,velocity,channel);
      break;
      case 3:
         synthSamplerAuthenticStrings_Sampler_noteOn(_ctx.voice3,note,velocity,channel);
      break;
    
   }
};

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_sendNoteOff_type;

static_inline void synthSamplerAuthenticStrings_Poly_sendNoteOff_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_sendNoteOff(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, int voice, int note, int channel){
   switch(voice) {
      case 0:
         synthSamplerAuthenticStrings_Sampler_noteOff(_ctx.voice0,note,channel);
      break;
      case 1:
         synthSamplerAuthenticStrings_Sampler_noteOff(_ctx.voice1,note,channel);
      break;
      case 2:
         synthSamplerAuthenticStrings_Sampler_noteOff(_ctx.voice2,note,channel);
      break;
      case 3:
         synthSamplerAuthenticStrings_Sampler_noteOff(_ctx.voice3,note,channel);
      break;
    
   }
};

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_setSamplerate_type;

static_inline void synthSamplerAuthenticStrings_Poly_setSamplerate_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_setSamplerate(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, fix16_t fs){
   synthSamplerAuthenticStrings_Sampler_setSamplerate(_ctx.voice0,fs);
   synthSamplerAuthenticStrings_Sampler_setSamplerate(_ctx.voice1,fs);
   synthSamplerAuthenticStrings_Sampler_setSamplerate(_ctx.voice2,fs);
   synthSamplerAuthenticStrings_Sampler_setSamplerate(_ctx.voice3,fs);
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetSustain_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetSustain_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetSustain(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, uint8_t flag){
   synthSamplerAuthenticStrings_Sampler_setSustain(_ctx.voice0,flag);
   synthSamplerAuthenticStrings_Sampler_setSustain(_ctx.voice1,flag);
   synthSamplerAuthenticStrings_Sampler_setSustain(_ctx.voice2,flag);
   synthSamplerAuthenticStrings_Sampler_setSustain(_ctx.voice3,flag);
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetLoop_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetLoop_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetLoop(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, uint8_t flag){
   synthSamplerAuthenticStrings_Sampler_setLoop(_ctx.voice0,flag);
   synthSamplerAuthenticStrings_Sampler_setLoop(_ctx.voice1,flag);
   synthSamplerAuthenticStrings_Sampler_setLoop(_ctx.voice2,flag);
   synthSamplerAuthenticStrings_Sampler_setLoop(_ctx.voice3,flag);
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetLoopStart_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetLoopStart_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetLoopStart(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, int value){
   synthSamplerAuthenticStrings_Sampler_setLoopStart(_ctx.voice0,value);
   synthSamplerAuthenticStrings_Sampler_setLoopStart(_ctx.voice1,value);
   synthSamplerAuthenticStrings_Sampler_setLoopStart(_ctx.voice2,value);
   synthSamplerAuthenticStrings_Sampler_setLoopStart(_ctx.voice3,value);
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetLoopEnd_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetLoopEnd_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetLoopEnd(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, int value){
   synthSamplerAuthenticStrings_Sampler_setLoopEnd(_ctx.voice0,value);
   synthSamplerAuthenticStrings_Sampler_setLoopEnd(_ctx.voice1,value);
   synthSamplerAuthenticStrings_Sampler_setLoopEnd(_ctx.voice2,value);
   synthSamplerAuthenticStrings_Sampler_setLoopEnd(_ctx.voice3,value);
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthGetLoop_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthGetLoop_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerAuthenticStrings_Poly_synthGetLoop(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx){
   return synthSamplerAuthenticStrings_Sampler_getLoop(_ctx.voice0);
};

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthGetLoopStart_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthGetLoopStart_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerAuthenticStrings_Poly_synthGetLoopStart(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx){
   return synthSamplerAuthenticStrings_Sampler_getLoopStart(_ctx.voice0);
};

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthGetLoopEnd_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthGetLoopEnd_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerAuthenticStrings_Poly_synthGetLoopEnd(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx){
   return synthSamplerAuthenticStrings_Sampler_getLoopEnd(_ctx.voice0);
};

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthGetSize_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthGetSize_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerAuthenticStrings_Poly_synthGetSize(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx){
   return synthSamplerAuthenticStrings_Sampler_getSampleSize(_ctx.voice0);
};

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthGetNbWavetables_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthGetNbWavetables_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerAuthenticStrings_Poly_synthGetNbWavetables(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx){
   return 0;
};

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetModulatorWavetable_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorWavetable_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorWavetable(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, fix16_t wavetableIdx){
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetModulatorWavetablePhase_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorWavetablePhase_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorWavetablePhase(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, fix16_t phaseIdx){
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetCarrierWavetable_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetCarrierWavetable_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetCarrierWavetable(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, fix16_t wavetableIdx){
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetCarrierWavetablePhase_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetCarrierWavetablePhase_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetCarrierWavetablePhase(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, fix16_t phaseIdx){
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetModulatorRatio_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorRatio_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorRatio(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, fix16_t ratio){
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetCarrierRatio_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetCarrierRatio_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetCarrierRatio(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, fix16_t ratio){
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetModulatorLevel_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorLevel_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorLevel(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, fix16_t level){
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetModulatorTargetLevel_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorTargetLevel_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorTargetLevel(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, uint8_t targetLevel){
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetModulatorPhaseShift_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorPhaseShift_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorPhaseShift(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, fix16_t ratio){
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetModulatorFeedback_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorFeedback_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorFeedback(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, fix16_t ratio){
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetModulatorADSR_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorADSR_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetModulatorADSR(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_synthSetCarrierADSR_type;

static_inline void synthSamplerAuthenticStrings_Poly_synthSetCarrierADSR_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_synthSetCarrierADSR(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
}

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_shouldLeftOvers_type;

static_inline void synthSamplerAuthenticStrings_Poly_shouldLeftOvers_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerAuthenticStrings_Poly_shouldLeftOvers(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx){
   return _ctx.should_leftovers;
};

typedef synthSamplerAuthenticStrings_Poly__ctx_type_0 synthSamplerAuthenticStrings_Poly_default_type;

static_inline void synthSamplerAuthenticStrings_Poly_default_init(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Poly_default(synthSamplerAuthenticStrings_Poly__ctx_type_0 &_ctx);

typedef struct synthSamplerAuthenticStrings_Poly__ctx_type_1 {
   synthSamplerAuthenticStrings_Poly__ctx_type_0 _inst179;
} synthSamplerAuthenticStrings_Poly__ctx_type_1;

typedef synthSamplerAuthenticStrings_Poly__ctx_type_1 synthSamplerAuthenticStrings_Poly_dummy_type;

static_inline void synthSamplerAuthenticStrings_Poly__ctx_type_1_init(synthSamplerAuthenticStrings_Poly__ctx_type_1 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_1 &_ctx = _output_;
   synthSamplerAuthenticStrings_Poly__ctx_type_0_init(_ctx._inst179);
   
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_dummy_init(synthSamplerAuthenticStrings_Poly__ctx_type_1 &_output_){
   synthSamplerAuthenticStrings_Poly__ctx_type_1_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Poly_dummy(synthSamplerAuthenticStrings_Poly__ctx_type_1 &_ctx){
   fix16_t buff[256];
   synthSamplerAuthenticStrings_Buffer_buffer(buff);
   synthSamplerAuthenticStrings_Poly_runVoice(_ctx._inst179,0,0,buff);
}

typedef struct synthSamplerAuthenticStrings_Voice__ctx_type_0 {
   synthSamplerAuthenticStrings_Notes__ctx_type_0 voicesinactive;
   synthSamplerAuthenticStrings_Notes__ctx_type_0 voicesactive;
   fix16_t voices_ratio;
   int voices[4];
   synthSamplerAuthenticStrings_Notes__ctx_type_0 voiceinsactive;
   uint8_t reuse;
   synthSamplerAuthenticStrings_Poly__ctx_type_0 poly;
   int number_voices;
   int notes[128];
   uint8_t normalize;
   fix16_t leftovers_decay;
   fix16_t leftovers;
   int last_velocities[4];
   fix16_t last_values[4];
   fix16_t fs;
   fix16_t buffer_v3[256];
   fix16_t buffer_v2[256];
   fix16_t buffer_v1[256];
   fix16_t buffer_v0[256];
} synthSamplerAuthenticStrings_Voice__ctx_type_0;

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_process_type;

void synthSamplerAuthenticStrings_Voice__ctx_type_0_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_);

static_inline void synthSamplerAuthenticStrings_Voice_process_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

fix16_t synthSamplerAuthenticStrings_Voice_process(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx);

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_process_bufferTo_type;

static_inline void synthSamplerAuthenticStrings_Voice_process_bufferTo_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Voice_process_bufferTo(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, int nb, fix16_t (&oBuffer)[256]);

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_process_bufferTo_alt_type;

static_inline void synthSamplerAuthenticStrings_Voice_process_bufferTo_alt_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Voice_process_bufferTo_alt(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, int nb, fix16_t (&oBuffer)[256]);

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_setReuse_type;

static_inline void synthSamplerAuthenticStrings_Voice_setReuse_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_setReuse(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, uint8_t flag){
   _ctx.reuse = flag;
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_noteOff_type;

static_inline void synthSamplerAuthenticStrings_Voice_noteOff_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Voice_noteOff(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, int note, int channel);

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_noteOn_type;

static_inline void synthSamplerAuthenticStrings_Voice_noteOn_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Voice_noteOn(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, int note, int velocity, int channel);

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_setNbVoices_type;

static_inline void synthSamplerAuthenticStrings_Voice_setNbVoices_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Voice_setNbVoices(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, int nbvoices);

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_setNormalize_type;

static_inline void synthSamplerAuthenticStrings_Voice_setNormalize_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_setNormalize(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, uint8_t flag){
   _ctx.normalize = flag;
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_setSamplerate_type;

static_inline void synthSamplerAuthenticStrings_Voice_setSamplerate_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Voice_setSamplerate(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, fix16_t newFs);

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetSustain_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetSustain_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetSustain(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, uint8_t flag){
   synthSamplerAuthenticStrings_Poly_synthSetSustain(_ctx.poly,flag);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetLoop_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetLoop_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetLoop(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, uint8_t flag){
   synthSamplerAuthenticStrings_Poly_synthSetLoop(_ctx.poly,flag);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetLoopStart_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetLoopStart_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetLoopStart(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, int value){
   synthSamplerAuthenticStrings_Poly_synthSetLoopStart(_ctx.poly,value);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetLoopEnd_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetLoopEnd_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetLoopEnd(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, int value){
   synthSamplerAuthenticStrings_Poly_synthSetLoopEnd(_ctx.poly,value);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthGetLoop_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthGetLoop_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t synthSamplerAuthenticStrings_Voice_synthGetLoop(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx){
   return synthSamplerAuthenticStrings_Poly_synthGetLoop(_ctx.poly);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthGetLoopStart_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthGetLoopStart_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerAuthenticStrings_Voice_synthGetLoopStart(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx){
   return synthSamplerAuthenticStrings_Poly_synthGetLoopStart(_ctx.poly);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthGetLoopEnd_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthGetLoopEnd_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerAuthenticStrings_Voice_synthGetLoopEnd(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx){
   return synthSamplerAuthenticStrings_Poly_synthGetLoopEnd(_ctx.poly);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthGetSize_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthGetSize_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerAuthenticStrings_Voice_synthGetSize(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx){
   return synthSamplerAuthenticStrings_Poly_synthGetSize(_ctx.poly);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthGetNbWavetables_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthGetNbWavetables_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline int synthSamplerAuthenticStrings_Voice_synthGetNbWavetables(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx){
   return synthSamplerAuthenticStrings_Poly_synthGetNbWavetables(_ctx.poly);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetModulatorWavetable_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorWavetable_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorWavetable(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, fix16_t wavetableIdx){
   synthSamplerAuthenticStrings_Poly_synthSetModulatorWavetable(_ctx.poly,wavetableIdx);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetModulatorWavetablePhase_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorWavetablePhase_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorWavetablePhase(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, fix16_t phaseIdx){
   synthSamplerAuthenticStrings_Poly_synthSetModulatorWavetablePhase(_ctx.poly,phaseIdx);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetCarrierWavetable_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetCarrierWavetable_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetCarrierWavetable(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, fix16_t wavetableIdx){
   synthSamplerAuthenticStrings_Poly_synthSetCarrierWavetable(_ctx.poly,wavetableIdx);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetCarrierWavetablePhase_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetCarrierWavetablePhase_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetCarrierWavetablePhase(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, fix16_t phaseIdx){
   synthSamplerAuthenticStrings_Poly_synthSetCarrierWavetablePhase(_ctx.poly,phaseIdx);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetModulatorRatio_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorRatio_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorRatio(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, fix16_t ratio){
   synthSamplerAuthenticStrings_Poly_synthSetModulatorRatio(_ctx.poly,ratio);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetCarrierRatio_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetCarrierRatio_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetCarrierRatio(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, fix16_t ratio){
   synthSamplerAuthenticStrings_Poly_synthSetCarrierRatio(_ctx.poly,ratio);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetModulatorLevel_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorLevel_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorLevel(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, fix16_t level){
   synthSamplerAuthenticStrings_Poly_synthSetModulatorLevel(_ctx.poly,level);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetModulatorTargetLevel_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorTargetLevel_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorTargetLevel(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, uint8_t targetLevel){
   synthSamplerAuthenticStrings_Poly_synthSetModulatorTargetLevel(_ctx.poly,targetLevel);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetModulatorPhaseShift_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorPhaseShift_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorPhaseShift(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, fix16_t ratio){
   synthSamplerAuthenticStrings_Poly_synthSetModulatorPhaseShift(_ctx.poly,ratio);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetModulatorFeedback_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorFeedback_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorFeedback(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, fix16_t ratio){
   synthSamplerAuthenticStrings_Poly_synthSetModulatorFeedback(_ctx.poly,ratio);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetModulatorADSR_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorADSR_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetModulatorADSR(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
   synthSamplerAuthenticStrings_Poly_synthSetModulatorADSR(_ctx.poly,a,d,s,r);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_synthSetCarrierADSR_type;

static_inline void synthSamplerAuthenticStrings_Voice_synthSetCarrierADSR_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_synthSetCarrierADSR(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx, fix16_t a, fix16_t d, fix16_t s, fix16_t r){
   synthSamplerAuthenticStrings_Poly_synthSetCarrierADSR(_ctx.poly,a,d,s,r);
};

typedef synthSamplerAuthenticStrings_Voice__ctx_type_0 synthSamplerAuthenticStrings_Voice_default_type;

static_inline void synthSamplerAuthenticStrings_Voice_default_init(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_0_init(_output_);
   return ;
}

void synthSamplerAuthenticStrings_Voice_default(synthSamplerAuthenticStrings_Voice__ctx_type_0 &_ctx);

typedef struct synthSamplerAuthenticStrings_Voice__ctx_type_1 {
   synthSamplerAuthenticStrings_Voice__ctx_type_0 _inst275;
   synthSamplerAuthenticStrings_Voice__ctx_type_0 _inst1b9;
} synthSamplerAuthenticStrings_Voice__ctx_type_1;

typedef synthSamplerAuthenticStrings_Voice__ctx_type_1 synthSamplerAuthenticStrings_Voice_dummy_type;

void synthSamplerAuthenticStrings_Voice__ctx_type_1_init(synthSamplerAuthenticStrings_Voice__ctx_type_1 &_output_);

static_inline void synthSamplerAuthenticStrings_Voice_dummy_init(synthSamplerAuthenticStrings_Voice__ctx_type_1 &_output_){
   synthSamplerAuthenticStrings_Voice__ctx_type_1_init(_output_);
   return ;
}

static_inline void synthSamplerAuthenticStrings_Voice_dummy(synthSamplerAuthenticStrings_Voice__ctx_type_1 &_ctx){
   fix16_t buff[256];
   synthSamplerAuthenticStrings_Buffer_buffer(buff);
   synthSamplerAuthenticStrings_Voice_process_bufferTo(_ctx._inst1b9,0,buff);
   synthSamplerAuthenticStrings_Voice_process_bufferTo_alt(_ctx._inst275,0,buff);
}



#endif // SYNTHSAMPLERAUTHENTICSTRINGS_H
